name: Deployment Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  MONGODB_TEST_CNN: ${{ secrets.MONGODB_TEST_CNN }}
  SECRETORPRIVATEKEY: ${{ secrets.SECRETORPRIVATEKEY }}
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  avoid_reduncy:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: npm
          node-version: 18
          cache-dependency-path: package-lock.json
      - name: Install dependencies
        run: npm ci

  # lint:
  #   needs: install
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - uses: actions/setup-node@v3
  #       with:
  #         cache: npm
  #         node-version: 18
  #         cache-dependency-path: package-lock.json
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Lint
  #       run: npm run lint

  # build:
  #   needs: install
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - uses: actions/setup-node@v3
  #       with:
  #         cache: npm
  #         node-version: 18
  #         cache-dependency-path: package-lock.json
  #     - name: Install dependencies
  #       run: npm ci
  #     - name: Build
  #       run: npm run build
  #     - uses: actions/upload-artifact@v3
  #       with:
  #         name: build
  #         path: ./app/build

  # tests_e2e:
  #   needs: [lint, build]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #       with:
  #         fetch-depth: 0
  #     - uses: actions/setup-node@v3
  #       with:
  #         cache: npm
  #         node-version: 18
  #         cache-dependency-path: package-lock.json
  #     - name: Install dependencies
  #       run: npm ci
  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: build
  #         path: ./app/build
  #     - name: E2E Tests
  #       uses: cypress-io/github-action@v3
  #       with:
  #         command: npm run test:e2e
  #         start: npm run start-test
  #         wait-on: http://localhost:8080
  #         install: false

  deploy:
    # needs: [tests_e2e]
    needs: install
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: chmod +x /usr/bin/*
      - run: flyctl deploy --remote-only
