name: Deployment Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize]

env:
  MONGODB_TEST_CNN: ${{ secrets.MONGODB_TEST_CNN }}
  SECRETORPRIVATEKEY: ${{ secrets.SECRETORPRIVATEKEY }}

jobs:
  avoid_reduncy:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  install:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: "16"

      # - uses: actions/setup-node@v2
      #   with:
      #     cache: npm
      #     node-version: "16"
      #     cache-dependency-path: ./api/package-lock.json

      - name: Install dependencies
        run: npm install

  lint:
    needs: install
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: "16"
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint

  build:
    needs: install
    defaults:
      run:
        working-directory: ./app
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: "16"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: build
          path: ./app/build

  e2e:
    needs: [lint, build]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v2
        with:
          cache: npm
          node-version: "16"
      - name: Install dependencies
        working-directory: ./api
        run: npm install

      - uses: actions/download-artifact@v2
        with:
          name: build
          path: build

      - name: Prepare E2E Tests
        working-directory: ./api
        run: npm run test &

      - name: E2E Tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: ./app
          command: npm run test:e2e
          # start: npm run start-test
          # wait-on: http://localhost:8080

  deploy:
    needs: [e2e]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Lint
        run: npm run lint
      - name: Deploy to heroku
        if: ${{ github.event_name == 'push' }}
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          heroku_email: ${{secrets.HEROKU_API_EMAIL}}
          healthcheck: "https://${{secrets.HEROKU_APP}}.herokuapp.com/healt"
          rollbackonhealtcheckfailed: true
